import { Montserrat } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "AK Enterprises",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Nav />
        <div>{children}</div>
      </body>
    </html>
  );
}
